MvcProjectCamp/Controllers/WriterPanelMessageController.cs
using System;

using System.Linq;
using System.Web.Mvc;
using Business.Concrete;
using Business.ValidationRules.FluentValidation;
using DataAccess.Concrete.EntityFramework;
using Entity.Concrete;
using FluentValidation.Results;

namespace MvcProjectCamp.Controllers
{
    public class WriterPanelMessageController : Controller
    {
        private MessageManager _messageManager = new MessageManager(new EfMessageDal());
        private ContactManager _contactManager = new ContactManager(new EfContactDal());
        private MessageValidator messageValidator = new MessageValidator();
        public ActionResult Inbox()
        {
            string userEmail = (string)Session["WriterMail"];
            var result = _messageManager.GetListInbox(userEmail);
            return View(result);
        }
        public ActionResult SendBox()
        {
            string userEmail = (string)Session["WriterMail"];
            var result = _messageManager.GetListSendbox(userEmail);
            return View(result);
        }
        public PartialViewResult ContactSideBarPartial()
        {
            string userEmail = (string)Session["WriterMail"];
            var contactList = _contactManager.GetAll();
            ViewBag.contactCount = contactList.Count();
            var listResult = _messageManager.GetListSendbox(userEmail);
            var sendList = listResult.FindAll(x => x.isDraft == false);
            ViewBag.sendCount = sendList.Count();
            var listResult2 = _messageManager.GetListInbox(userEmail);
            ViewBag.inboxCount = listResult2.Count();
            var drafList = listResult.FindAll(x => x.isDraft == true);
            ViewBag.draftCount = drafList.Count();
            return PartialView();
        }
        public ActionResult GetInBoxMessageDetails(int id)
        {
            var result = _messageManager.GetById(id);
            return View(result);
        }
        public ActionResult GetSendBoxMessageDetails(int id)
        {
            var result = _messageManager.GetById(id);
            return View(result);
        }
        [HttpGet]
        public ActionResult NewMessage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewMessage(Message message, string button)
        {
            string userEmail = (string)Session["WriterMail"];
            ValidationResult results = messageValidator.Validate(message);
            if (button == "draft")
            {

                results = messageValidator.Validate(message);
                if (results.IsValid)
                {
                    message.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                    message.SenderMail = userEmail;
                    message.isDraft = true;
                    _messageManager.Add(message);
                    return RedirectToAction("Draft");
                }
                else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }
                }
            }
            else if (button == "save")
            {
                results = messageValidator.Validate(message);
                if (results.IsValid)
                {
                    message.MessageDate = DateTime.Now;
                    message.SenderMail = userEmail;
                    message.isDraft = false;
                    _messageManager.Add(message);
                    return RedirectToAction("SendBox");
                }
                else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }
                }
            }
            return View();
        }
        public ActionResult Draft()
        {
            string userEmail = (string)Session["WriterMail"];
            var sendList = _messageManager.GetListSendbox(userEmail);
            var draftList = sendList.FindAll(x => x.isDraft == true);
            return View(draftList);
        }

        public ActionResult GetDraftMessageDetails(int id)
        {
            var Values = _messageManager.GetById(id);
            return View(Values);
        }
    }
}

MvcProjectCamp/Views/WriterPanelMessage/Draft.cshtml
@using Entity.Concrete
@model List<Message>
@{
    ViewBag.Title = "SendBox";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("ContactSideBarPartial", "WriterPanelMessage")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Taslak Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail kutusunda ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="" id="check1">
                                                    <label for="check1"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="/Message/GetDraftMessageDetails/@item.Id"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="/Message/GetDraftMessageDetails/@item.Id">@item.ReceiverMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b> - @item.MessageContent.Substring(0, 30)...
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">5 mins ago</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

MvcProjectCamp/Views/WriterPanelMessage/GetDraftMessageDetails.cshtml
@{
    ViewBag.Title = "GetDraftMessageDetails";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

@model Entity.Concrete.Message

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Gelen Mesaj Detayları</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("ContactSideBarPartial", "WriterPanelMessage")
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesajı Oku</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu: @Html.DisplayFor(x => x.Subject)</h5>
                                <br />
                                <h6>
                                    Alıcı: @Html.DisplayFor(x => x.ReceiverMail)
                                    <span class="mailbox-read-time float-right">
                                        @Model.MessageDate.ToString("dd-MMM-yyyy")
                                    </span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>@Html.Raw(Model.MessageContent)</p>
                                @*<p>@Html.DisplayFor(x => x.MessageContent)</p>*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MvcProjectCamp/Views/WriterPanelMessage/GetInBoxMessageDetails.cshtml
@model Entity.Concrete.Message
@{
    ViewBag.Title = "GetInBoxMessageDetails";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesajlar</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("ContactSideBarPartial", "WriterPanelMessage")
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesajı Oku</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>


                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu : @Html.DisplayFor(x => x.Subject)</h5>


                                <h6>
                                    Kimden : @Html.DisplayFor(x => x.SenderMail)
                                    <span class="mailbox-read-time float-right">  @Model.MessageDate.ToString("dd-MMM-yyyy")</span>
                                </h6>

                            </div>
                            <div class="mailbox-read-message">
                                <p>@Html.DisplayFor(x => x.MessageContent)</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MvcProjectCamp/Views/WriterPanelMessage/GetSendBoxMessageDetails.cshtml
@model Entity.Concrete.Message
@{
    ViewBag.Title = "GetSendBoxMessageDetails";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Gönderilen Mesajlar</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("ContactSideBarPartial", "WriterPanelMessage")
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesajı Oku</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>


                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu : @Html.DisplayFor(x => x.Subject)</h5>


                                <h6>
                                    Kime : @Html.DisplayFor(x => x.ReceiverMail)
                                    <span class="mailbox-read-time float-right">  @Model.MessageDate.ToString("dd-MMM-yyyy")</span>
                                </h6>

                            </div>
                            <div class="mailbox-read-message">
                                <p>@Html.DisplayFor(x => x.MessageContent)</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MvcProjectCamp/Views/WriterPanelMessage/Inbox.cshtml
@using Entity.Concrete
@model List<Message>
@{
    ViewBag.Title = "Inbox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>

            </div>
        </div>
    </section>
    <section class="content">
        <div class="row">
            @Html.Action("ContactSideBarPartial", "WriterPanelMessage")
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gelen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mailde ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="" id="check1">
                                                    <label for="check1"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="/WriterPanelMessage/GetInBoxMessageDetails/@item.Id"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="/WriterPanelMessage/GetInBoxMessageDetails/@item.Id">@item.SenderMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b> - @item.MessageContent.Substring(0, 20)...
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">  @(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</body>
</html>

MvcProjectCamp/Views/WriterPanelMessage/NewMessage.cshtml
@model Entity.Concrete.Message
@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1></h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("ContactSideBarPartial", "WriterPanelMessage")
                <!-- /.col -->
                <div class="col-md-9">
                    @using (Html.BeginForm("NewMessage", "WriterPanelMessage", FormMethod.Post))
                    {
                        <div class="card card-primary card-outline">

                            <div class="card-header">
                                <h3 class="card-title">Yeni Mesaj Oluştur</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.Label("Alıcı Mail")
                                    @Html.TextBoxFor(x => x.ReceiverMail, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.ReceiverMail)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Konu")
                                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Subject)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Mesajınız")
                                    <textarea id="compose-textarea" name="MessageContent" class="form-control" style="height: 300px">                       
                                 </textarea>
                                    @Html.ValidationMessageFor(x => x.MessageContent)
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="submit" formmethod="post" name="button" value="draft" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet </button>
                                    <button type="submit" name="button" value="save" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder </button>
                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                            </div>
                            <!-- /.card-footer -->
                        </div>

                    }
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/docs/assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- Summernote -->
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <!-- Page specific script -->
    <script>
        $(function () {
            //Add text editor
            $('#compose-textarea').summernote()
        })
    </script>
</body>